### ISSUE TITLE
Customize table header style and td style

### ISSUE THREAD

**Issue by sadashivm** [ng-fullcalendar/ng-fullcalendar#114]
Hello,
I want to reduce the font-size for the header and also reduce the height of each cell (td).
For Example, I updated tbody tr height:
.fc-basic-view .fc-body .fc-row {
    min-height: 2em !important;
}
which is not reflecting.

Please tell me how to customize all the classes.

**Comment by jmarlett93** [comment]
Into what css sheet are you adding the styles? Angular enforces scope on css to the associated component. So in the stackblitz example, the app.component.css wont apply to the html generated inside <ng-calendar> because they are children in the ng-calendar scope.  If ng-calendar does not accept a style input, you could try global styles or the deprecated ng-deep.  https://angular.io/guide/component-styles

**Comment by irustm** [comment]
this issue deprecated.
fullcalendar@4.0.0 released without Jquery,
try use ng-fullcalendar@2.0.0 with fulcalendar plugins
